org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Release signing config
RELEASE_STORE_FILE=release.keystore
RELEASE_STORE_PASSWORD=n3edsVsWants2026!
RELEASE_KEY_ALIAS=release
RELEASE_KEY_PASSWORD=n3edsVsWants2026!
